[package]
name = "sync-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde_json = "1"
sync-core = { path = "../sync-core" }
sync-protocol = { path = "../sync-protocol" }
sync-crypto = { path = "../sync-crypto" }
sync-storage = { path = "../sync-storage" }
sync-platform = { path = "../sync-platform" }
sync-transport = { path = "../sync-transport" }

[lints]
workspace = true
